export const dynamic = 'force-dynamic';
import { NextResponse } from "next/server";
import prisma from '@/lib/prisma';

async function ensureTables() {
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS epi_entregas (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cpf TEXT NOT NULL,
      item TEXT NOT NULL,
      qty_required INT DEFAULT 1,
      qty_delivered INT DEFAULT 0,
      deliveries JSONB DEFAULT '[]',
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(cpf, item)
    );
  `);
}

export async function GET(req: Request) {
  try {
    await ensureTables();
    const { searchParams } = new URL(req.url);
    const cpf = String(searchParams.get("cpf") || "");
    if (!cpf) return NextResponse.json({ ok: false, error: "cpf obrigatório" }, { status: 200 });
    const rows = await prisma.$queryRawUnsafe<any[]>(`select * from epi_entregas where cpf = $1`, cpf);
    return NextResponse.json({ ok: true, rows });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}

export async function POST(req: Request) {
  try {
    await ensureTables();
    const body = await req.json();
    const cpf = String(body?.cpf || "").replace(/\D/g,'');
    const item = String(body?.item || "");
    const qty = Number(body?.qty ?? 1);
    const date = String(body?.date || "").substring(0,10) || new Date().toISOString().substring(0,10);
    const required = Number(body?.qty_required ?? 1) || 1;

    if (!cpf || !item) return NextResponse.json({ ok: false, error: "cpf e item são obrigatórios" }, { status: 200 });

    const up = await prisma.$queryRawUnsafe<any[]>(`
      INSERT INTO epi_entregas (cpf, item, qty_required, qty_delivered, deliveries)
      VALUES ($1, $2, $3, $4, jsonb_build_array(jsonb_build_object('date', $5, 'qty', $6)))
      ON CONFLICT (cpf, item) DO UPDATE SET
        qty_required = EXCLUDED.qty_required,
        qty_delivered = epi_entregas.qty_delivered + $6,
        deliveries = epi_entregas.deliveries || jsonb_build_array(jsonb_build_object('date', $5, 'qty', $6)),
        updated_at = now()
      RETURNING *;
    `, cpf, item, required, qty, date, qty);
    return NextResponse.json({ ok: true, row: up?.[0] ?? null });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}
