import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function ensureTables() {
  // Tabela de colaboradores manuais
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS epi_manual_colab (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cpf TEXT NOT NULL UNIQUE,
      matricula TEXT,
      nome TEXT,
      funcao TEXT,
      unidade TEXT,
      regional TEXT,
      admissao DATE,
      demissao DATE,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );
  `);
}

function toDateOrNull(s: any): string | null {
  if (!s) return null;
  const str = String(s);
  // try yyyy-mm-dd
  let m = str.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (m) return `${m[1]}-${m[2]}-${m[3]}`;
  // dd/mm/yyyy
  m = str.match(/^(\d{2})\/(\d{2})\/(\d{4})/);
  if (m) return `${m[3]}-${m[2]}-${m[1]}`;
  // yyyymmdd
  m = str.match(/^(\d{4})(\d{2})(\d{2})$/);
  if (m) return `${m[1]}-${m[2]}-${m[3]}`;
  return null;
}

export async function GET() {
  try {
    await ensureTables();
    const rows = await prisma.$queryRawUnsafe<any[]>(`select * from epi_manual_colab order by created_at desc`);
    return NextResponse.json({ ok: true, rows });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}

export async function POST(req: Request) {
  try {
    await ensureTables();
    const body = await req.json();
    const cpf = String(body?.cpf || "").replace(/\D/g, "");
    if (!cpf) return NextResponse.json({ ok: false, error: "CPF obrigatório" }, { status: 200 });
    const data = {
      cpf,
      matricula: body?.matricula ? String(body.matricula) : null,
      nome: body?.nome ? String(body.nome) : null,
      funcao: body?.funcao ? String(body.funcao) : null,
      unidade: body?.unidade ? String(body.unidade) : null,
      regional: body?.regional ? String(body.regional) : null,
      admissao: toDateOrNull(body?.admissao),
      demissao: toDateOrNull(body?.demissao),
    };
    const up = await prisma.$queryRawUnsafe<any[]>(`
      INSERT INTO epi_manual_colab (cpf, matricula, nome, funcao, unidade, regional, admissao, demissao)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      ON CONFLICT (cpf) DO UPDATE SET
        matricula = EXCLUDED.matricula,
        nome = EXCLUDED.nome,
        funcao = EXCLUDED.funcao,
        unidade = EXCLUDED.unidade,
        regional = EXCLUDED.regional,
        admissao = EXCLUDED.admissao,
        demissao = EXCLUDED.demissao,
        updated_at = now()
      RETURNING *;
    `, data.cpf, data.matricula, data.nome, data.funcao, data.unidade, data.regional, data.admissao, data.demissao);
    return NextResponse.json({ ok: true, row: up?.[0] ?? null });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}
